### ISSUE TITLE
Importing definitions is not working for Python

### ISSUE THREAD

**Issue by nilansaha** [namely/docker-protoc#235]
So, I followed the commands given in the test to try to generate python files for the proto definitions in the`all/test/` folder

Here is the command I used which is almost the same as the one used in the test file at `all/test.sh`

`docker run -v `pwd`:/defs namely/protoc-all -f all/test/test.proto -i all/test/ -l python`

But when I try to import the generated python file it does not work because apparently the imported definitions are not there or something.

`>>> import gen.pb_python.all.test.test_pb2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nilan/Desktop/docker-protoc/gen/pb_python/all/test/test_pb2.py", line 16, in <module>
    from all.test import include_pb2 as all_dot_test_dot_include__pb2
ImportError: cannot import name 'include_pb2' from 'all.test' (unknown location)`

**Comment by ido-namely** [comment]
Hi @nilansaha,
I'm sorry for the late response.
If this issue is still relevant, would you mind explaining the difference between your invocation and the test?
Perhaps you can also share a  proto file definitions to reproduce he issue.
